redis:
  image: redis
db:
  image: postgres:9.4
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
vote:
  build: ./vote
  ports:
    - 5000:80
  links:
    - redis:redis
result:
  build: ./result
  ports:
    - 5001:80
  links:
    - redis:redis
    - db:db
worker:
  build: ./worker
  links:
    - redis:redis
    - db:db
