redis:
  image: redis
db:
  image: postgres:9.4
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
vote:
  image: vote-app
  ports:
    - 5000:80
  links:
    - redis:redis
result:
  image: result-app
  ports:
    - 5001:80
  links:
    - redis:redis
    - db:db
worker:
  image: worker-app
  links:
    - redis:redis
    - db:db
